### ISSUE TITLE
Skipping python installation?

### ISSUE THREAD

**Issue by IdanAdar** [jfloff/alpine-python#11]
Hello, novice question here...
Given the following Dockerfile, can I assure that Python won't be installed on each `docker build` run? That is, that after its first-time installation it should suffice to not be repeated again and again?

In general, I'd like to add python to this Docker image, but just the bare-minimum that is needed, in order to preserve the smallest image size possible... it seems that the below installs quite a lot?

```
FROM node:6.9.4-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install python
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    && pip install virtualenv \
    && rm -rf /var/cache/apk/*

# Use .npmrc 
COPY ./.npmrc /usr/src/app
ARG NPM_TOKEN  

# Will prevent npm install if nothing has changed
COPY ./package.json /usr/src/app
RUN cd /usr/src/app && npm install

# Bundle app source
COPY . /usr/src/app
 
EXPOSE 8080
CMD [ "npm", "start" ]
```

**Comment by IdanAdar** [comment]
Looks like at least `RUN apk add --update python py-pip` makes the installation lighter, but then the installation of the required node module fails with: 

> Binary has a problem: Error: Error relocating /usr/src/app/node_modules/node-sass/vendor/linux-x64-48/binding.node: __strtod_internal: symbol not found

**Comment by jfloff** [comment]
This doesn't appear to be related with the repo itself, but I'll try to answer anyway. I'll be closing the issue but feel free to ask more questions.

When you build an image in Docker it will cache layers (each instructions on the Dockerfile) that haven't changed. Also, when one of the instructions are changed, all the ones below will have to run again. Moreover, there are certain instructions that don't allow caching (COPY and ADD e.g.). For more info check [dockerfile refence](https://docs.docker.com/engine/reference/builder/#environment-replacement). 

Regarding the error, it feels to me it's not a python problem: `gyp ERR! stack Error: not found: make`. This looks the problem to me.

Hope I helped. Feel free to ask any more questions.
