### ISSUE TITLE
how to install mysqlclient? 

### ISSUE THREAD

**Issue by unknowfly** [jfloff/alpine-python#13]
I use 2.7-onbuild to make a Dockerfile and mysqlclient is in my requirements,  but it faild to install mysqlclient, this is the logs 

Collecting mysqlclient==1.3.9 (from -r requirements.txt (line 2))
  Downloading mysqlclient-1.3.9.tar.gz (81kB)
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zQwRaV/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

Should I install some dependences first?

**Comment by jfloff** [comment]
This has nothing to do with this image in particular, hence I'm closing.

Still, you are installing the python mysql python, but did you installed mysql-server? Try google that error, first result came up with a pretty good answer.
