### ISSUE TITLE
Travis CI runs out of memory since latest docker image update (17-11-2017)

### ISSUE THREAD

**Issue by snoepkast** [jfloff/alpine-python#16]
Hey there,

I see in the commit history that the latest change to this repo was 6 months ago, however according to dockerhub the latest build was done last friday. Since that time our CI has been broken with stalled builds. After debugging it turned out that we run out of memory.

Do you have any idea what could cause this? And how to fix this?

Thanks in advance

**Comment by snoepkast** [comment]
We're using 2.7, if you want to take a look at our dockerfile, it's [here](https://github.com/HelloLily/hellolily/blob/develop/Dockerfile). The Ci we're using is Travis (also contacted them about it), builds can be found [here](https://travis-ci.org/HelloLily/hellolily/branches).

After local tests it doesn't seem like the memory has actually increased though, we tested by building using the cached image and the new one while monitoring with `docker stats`. 

Maybe you have a clue what goes wrong? The builds just stall...

**Comment by jfloff** [comment]
I've cloned your repo, and I'm trying to build the image locally to see if I see any errors while building. I'll be back when its done

**Comment by jfloff** [comment]
I've builded the image without any problem. I've looked through your Ci logs and it seems that its hanging perhaps on the `wait-for-it` script. I'm running the `docker-compose` now to do a couple of tests.

**Comment by snoepkast** [comment]
Ah yeah we've noticed that now too, it appears to be the exit statement or something (before we updated our dependencies it stalled in the middle of the `pip install gevent` so maybe that has exit too). Trying it now with the new docker healthchecks.

**Comment by jfloff** [comment]
I was able to run the dockerfile and run the tests directly (`python manage.py test --with-coverage --cover-erase --cover-package=lily`), so I would say something is wrong with the `wait-for-it`. 

I went to its repo, and found out [this commit](https://github.com/vishnubob/wait-for-it/commit/8ed92e8cab83cfed76ff012ed4a36cef74b28096) from 4 months ago that has a bug fix for when you pass parameters. I've checked and you indeed pass parameters `wait-for-it.sh -b db:5432` and your version of the script is before that commit. Maybe you could test updating the `wait-for-it` script and rerun the build?
