### ISSUE TITLE
Gevent doesn't install

### ISSUE THREAD

**Issue by snoepkast** [jfloff/alpine-python#17]
Just a heads up, since gevent is specifically mentioned in the readme as a package that should be installable. Probably the same issue as with the `wait-for-it.sh`, the build just hangs:

Dockerfile
```Dockerfile
from jfloff/alpine-python:2.7

RUN pip install gevent
```

Shell
```bash
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : from jfloff/alpine-python:2.7
 ---> e96b6ec2e90a
Step 2/2 : RUN pip install gevent
 ---> Running in 63bfde9be37e
Collecting gevent
  Downloading gevent-1.2.2.tar.gz (3.1MB)
Collecting greenlet>=0.4.10 (from gevent)
  Downloading greenlet-0.4.12.tar.gz (57kB)
Installing collected packages: greenlet, gevent
  Running setup.py install for greenlet: started
    Running setup.py install for greenlet: finished with status 'done'
  Running setup.py install for gevent: started
```

The process just hangs here eternally.

I don't know if this is an alpine linux thingy or if it's caused by something installed in this repo. Also don't know who to talk to about fixing this.

**Comment by jfloff** [comment]
Thanks for the heads up! I'll dig around to see if I find something!

**Comment by jfloff** [comment]
I think this is an alpine issue. I was able to install gevent using the following commands:
```sh
# Add edge community repository
$ echo "@edge-community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
$ apk update
# Install gevent package
$ apk add py-gevent
# Install with pip
$ pip install gevent

**Comment by jfloff** [comment]
Any feedback regarding this?

**Comment by snoepkast** [comment]
Ah yeah sorry, adding the apk install fixes it. Just too bad it's an extra install.
