### ISSUE TITLE
Fails to build image - unable to find entrypoint.sh

### ISSUE THREAD

**Issue by filtoid** [jfloff/alpine-python#2]
Pulling the tag 3.4-onbuild appears to not work.

`FROM jfloff/alpine-python:3.4-onbuild`

results in 

> Sending build context to Docker daemon 52.74 kB
> Step 1 : FROM jfloff/alpine-python:3.4-onbuild
> 3.4-onbuild: Pulling from jfloff/alpine-python
> 
> c0cb142e4345: Pull complete
> 9220b57f4f62: Pull complete
> Digest: sha256:833747868f7c9da014e1906f2a7197e40267d8fa5a9601d328a6a670247e419a
> Status: Downloaded newer image for jfloff/alpine-python:3.4-onbuild
> \# Executing 3 build triggers...
> Step 1 : COPY requirements.txt /tmp/requirements.txt
> Step 1 : RUN /entrypoint.sh -r /tmp/requirements.txt
>  ---> Running in 024892bbb802
> /bin/sh: /entrypoint.sh: not found
> The command '/bin/sh -c /entrypoint.sh -r /tmp/requirements.txt' returned a non-zero code: 127

I may be doing something wrong but when I switch to 3.4-slim it works as expected which leads me to suspect a missing file in the image tag.

**Comment by jfloff** [comment]
The `slim` images are currently buggy due to a Docker Hub bug : docker/hub-feedback#811

```
 ---> 6b0028d692a1
Removing intermediate container f41605ecacda
Step 5 : COPY entrypoint.sh /entrypoint.sh
Removing intermediate container 50e001ab56b0
stat /var/lib/docker/overlay/c05173b011289324ac274a289e1916137f142d82cba63f04fd1a829375399113/merged/entrypoint.sh: no such file or directory
```

Hang on tight!

**Comment by filtoid** [comment]
Ok, thanks for following up so quickly. :)

**Comment by jfloff** [comment]
It appears that all images have passed the build on Docker Hub. Could you check if its working now?

**Comment by filtoid** [comment]
It is now reporting a permission denied error.

```
Sending build context to Docker daemon 55.81 kB
Step 1 : FROM jfloff/alpine-python:3.4-onbuild
3.4-onbuild: Pulling from jfloff/alpine-python
c0cb142e4345: Already exists
56f6c55fdd94: Pull complete
d6f0e37bf5bf: Pull complete
Digest: sha256:c6d56f52b4bd22d5bdb068d9eb31d03e32622ae5b1ad0e9569ce576ce249a701
Status: Downloaded newer image for jfloff/alpine-python:3.4-onbuild
# Executing 3 build triggers...
Step 1 : COPY requirements.txt /tmp/requirements.txt
Step 1 : RUN /entrypoint.sh -r /tmp/requirements.txt
 ---> Running in d1c8bb4a9bdb
/bin/sh: /entrypoint.sh: Permission denied
The command '/bin/sh -c /entrypoint.sh -r /tmp/requirements.txt' returned a non-zero code: 126
```

**Comment by jfloff** [comment]
That's was my fault :) Check again please!

(Sorry for making you my debug-buddy but I'm limited in my development environment at this moment)

**Comment by filtoid** [comment]
No problem, thanks for fixing it so quickly. 

Yep, that's successfully built. Thanks :)
