### ISSUE TITLE
requirements.txt installation fails.

### ISSUE THREAD

**Issue by apollo13** [jfloff/alpine-python#21]
I am generating my `requirements.txt`with checksums, ie:
```
cryptography==2.1.4 --hash=sha256:69285f5615507b6625f89ea1048addd1d9218585fb886eb90bdebb1d2b2d26f5  --hash=sha256:6cb1224da391fa90f1be524eafb375b62baf8d3df9690b32e8cc475ccfccee5e  
```
which requires that the file is loaded via `pip install -r …` not by catting and adding it to the pip argument list. What is the rationale for reading the requirements file instead of just passing it to pip?

**Comment by jfloff** [comment]
Sorry I didn't understand your issue... Could you show me how you are invoking pip? And also how do you want to invoke pip?

**Comment by apollo13** [comment]
@jfloff Sorry, I did not see that the above comment did not render properly; my requirements.txt includes hashes (as can be seen now in my previous comment). 

Currently pip is invoked like this: https://github.com/jfloff/alpine-python/blob/master/recent-onbuild/entrypoint.sh#L82

This does not work if the requirements file contains hashes (ie `--hash=sha256:…`), so I'd like pip to be invoked like `pip install -r requirements.txt` instead.

I hope I did explain it properly now, if not please tell me and I try to rephrase.

**Comment by jfloff** [comment]
@tprobinson Could you take a look at this issue?

**Comment by tprobinson** [comment]
Ah, this makes sense. I'm not sure why I did it this way originally, sort of ridiculous now that I think about it.

I think I can maintain the ability to use mixed flags (such as `-r` with `-p`) and still run Pip only once by concatenating the requirements file and the command line requirements into a temporary version. I'll try that out and update this issue when I've figured it out.

**Comment by apollo13** [comment]
Thanks!
