### ISSUE TITLE
Guidelines for multiple requirement files using onbuild image

### ISSUE THREAD

**Issue by rohit-zabbed** [jfloff/alpine-python#22]
Can you provide an example of using multiple requirement files eg. /requirements and /module/requirements as part of onbuild.
tried
```
FROM jfloff/alpine-python:2.7-onbuild
ENV PIP_REQUIREMENTS "requirements.txt nlp_submodule/requirements.txt"
ENV PORT 7000
EXPOSE 7000
ENTRYPOINT ["python"]
CMD ["run_service.py"]
```
But its not pulling up both the requirement files

**Comment by jfloff** [comment]
At the moment its not possible to install multiple requirements files at once _per se_. But you could sill make it work using [recursive requirements](https://pip.readthedocs.io/en/1.1/requirements.html#recursive-requirements). 

Just place the recursive call `-r nlp_submodule/requirements.txt` inside the main requirements.txt and it should do the trick.
