### ISSUE TITLE
requirement.txt fails to load...

### ISSUE THREAD

**Issue by holiman** [jfloff/alpine-python#23]
... when there are extra linebreaks in it 

Seems to have been broken with https://github.com/jfloff/alpine-python/commit/76c2abe472a0f3952a65c7ae9ad5f7686c00e575

This works:
```
requests
```
this does not
```
requests

```

**Comment by jfloff** [comment]
@tprobinson Could you take a look?

**Comment by tprobinson** [comment]
I can't seem to reproduce this. @holiman , could you share what happens when it breaks, and what other flags you're using? I tried this with `requests` and extra line breaks plus a `-p docopt` flag, but I didn't see a problem.

**Comment by jfloff** [comment]
Closing due to lack of feedback. @holiman feel free to reopen
