### ISSUE TITLE
Request: add --enable-shared for pyenv python installations

### ISSUE THREAD

**Issue by lwm** [jfloff/alpine-python#28]
Hi there, first off, thanks a lot for creating these images. We're using them over at [carbondoomsday](https://git.coop/lwm/carbondoomsday) since a while now and they've really made things easier to get small application images out the door quickly.

So, one issue I am seeing now, when running a `pipenv install` of my dependencies is:

```
...
ython3.6.a -lcrypt
    gcc: error: /usr/lib/python3.6.5/lib/python3.6/config-3.6m/libpython3.6.a: No such file or directory
    *** error linking uWSGI ***
```

The internet seems to think that `--enable-shared` should be passed when compiling the python:

  * https://github.com/pyenv/pyenv/issues/917
  * https://github.com/pytorch/pytorch/issues/997

This seems to be possible with `pyenv`, from their documentation:

> https://github.com/pyenv/pyenv/wiki#how-to-build-cpython-with---enable-shared

So, would you accept a pull request with `--enable-shared` tacked onto the `pyenv install`?

:+1:

**Comment by jfloff** [comment]
Of course! Bring it on 💪

**Comment by lwm** [comment]
Thanks! #29 has landed, should do the trick ...

**Comment by lwm** [comment]
Right, seems like #29 leads to pain. I've had anothe search around. It appears that I can just take the Alpine system package on this one (over at https://pkgs.alpinelinux.org/packages?name=uwsgi-python3&branch=edge) and avoid to do the compiling manually. I'll close this off now since I have this work around :+1:
