### ISSUE TITLE
update DIR to 3.8

### ISSUE THREAD

**Issue by pascalandy** [jfloff/alpine-python#38]
Good job on this!

I looked at the Dockerfile. It uses alpine:3.8 but it's parent directory's parent is 3.6
IMHO, you should update these directorys names :)

Cheers!

![screen shot 2018-12-14 at 11 18 50 am](https://user-images.githubusercontent.com/6694151/50014466-0d679380-ff92-11e8-968f-11012ff466e5.jpg)

**Comment by jfloff** [comment]
`3.6` and so on are the python versions, not Alpine's!

**Comment by pascalandy** [comment]
Oh! As you can see, I'm not a big python user ;-p

Thanks!
