### ISSUE TITLE
Unable to install postgresql-dev since last update

### ISSUE THREAD

**Issue by snoepkast** [jfloff/alpine-python#4]
Hello there,

We are unable to install the postgresql-dev package at version 9.5.4-r0 since the last version of your image. The error it gives:

```
ERROR: unsatisfiable constraints:
  postgresql-dev-9.6.0-r1:
    breaks: world[postgresql-dev=9.5.4-r0]
```

It's probably because you [replace](https://github.com/jfloff/alpine-python/blob/master/2.7/Dockerfile#L26) the default repositories with the edge ones?

[The Dockerfile](https://github.com/snoepkast/python-getting-started/blob/feature/test-feature-branch/Dockerfile)

**Comment by jfloff** [comment]
That's exactly it! Damn, I'm having all sorts of problems with packages dependencies in Alpine at the moment.

Could you please tell me:
- The command you are using to install specific version of postgresql-dev
- The tag you are trying to install to (3.4 or latest?)

**Comment by snoepkast** [comment]
Yeah sure!

```
FROM jfloff/alpine-python:2.7

RUN apk add --update \
    linux-headers \
    postgresql-dev=9.5.4-r0 \
    libxml2-dev \
    libxslt-dev \
    ncurses5-libs \
    rsync \
    nodejs \
    libjpeg-turbo-dev
```

We first had it like this, before the last update, but simply removing the @ edge didn't fix it:

```
FROM jfloff/alpine-python:2.7

RUN echo "@edge http://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
    apk add --update \
        postgresql-dev@edge=9.5.4-r0 \
        libxml2-dev \
        libxslt-dev \
        ncurses5-libs@edge \
        rsync \
        nodejs \
        libjpeg-turbo-dev@edge
```

**Comment by snoepkast** [comment]
Thanks for the quick fix!

2 more things:
 - I saw you added `linux-headers` to the 3.4 dockerfile; good idea to also do it for the 2.7 one?
 - Can you start a build on dockerhub so our ci can continue building?

**Comment by jfloff** [comment]
Sorry about the delay, I was on a meeting. I added `linux-headers` by mistake, but I'm keeping them since they were also on needed on the `slim`. Pushing that to docker hub now. Hang in there!

**Comment by jfloff** [comment]
I've already pushed to docker hub, but due to a know [bug](https://github.com/docker/hub-feedback/issues/811) I'm getting failed on a couple of images (namely slim and onbuild

**Comment by jfloff** [comment]
Just an update: After the DDoS issues on Friday, I got the `2.7`, `3.4` and `latest` tags to build on Docker Hub. But the remaining tags (all `onbuild` and `slim`) are still failing due to a known [bug](https://github.com/docker/hub-feedback/issues/811).

When you can verify that your ci is back, up and runing. Thanks!

**Comment by snoepkast** [comment]
Thanks, our CI works again :)

My compliments for your response time! And for the nice base image, even with dependencies built in (which the default python alpine hasn't) it results in a smaller and more capable image!

**Comment by jfloff** [comment]
Thank you so much for you feedback! Really glad you guys are using it :)

Any suggestions or problems feel free to drop a line! Cheers!
