### ISSUE TITLE
Dockerhub tags out of date

### ISSUE THREAD

**Issue by assembledadam** [jfloff/alpine-python#42]
FYI it looks like the tags for this are out of date, which seems to have been causing me troubles.

https://hub.docker.com/r/jfloff/alpine-python/tags

E.g. the latest tag is 10 months old, seemingly using an old Dockerfile (for Alpine 3.7).

**Comment by jfloff** [comment]
IIRC I've removed the tags for recent/latest and replaced them with the specific tag versions. That is, instead of `jfloff/alpine-python:latest` try `jfloff/alpine-python:3.6`

**Comment by jfloff** [comment]
Hey! I just realized how dumb I was and how little knowledge of Travis I have 🤦‍♂️ 

I just updated the `latest`, `latest-slim`, and `latest-onbuild`! Feel free to check them out ;)
