### ISSUE TITLE
jfloff/alpine-python:2.7-slim increased from 58.8MB to 96.9MB

### ISSUE THREAD

**Issue by alexisfrjp** [jfloff/alpine-python#45]
I rebuilt one of my Docker image and I saw the new size of the 2.7-slim increased a lot.

`jfloff/alpine-python                                  2.7-slim            7a1fffbf1673        11 hours ago        96.9MB`

Is it a problem or will it be the new optimized size?

Do you think it's possible to add an ID to the Docker image tag? Just to know at which Github commit the Docker image has been built.

**Comment by jfloff** [comment]
I’m still trying to figure the best way to keep the slim image small but compatible with some of the changes that occurred on the non-slim versions, namely the ability to have any python version without being tied to the alpine repos. Soon I will make some changes regarding this.

**Comment by jfloff** [comment]
Hi there! I just updated the images and `2.7-slim` is back to ~57Mb! If you found anything different with the new image please report! 👍 

Thank you!

**Comment by alexisfrjp** [comment]
Thank you for that!

**Comment by alexisfrjp** [comment]
Nevertheless, I get an error now with the same program I've used before.

`ImportError: Error loading shared library libffi.so.6: No such file or directory `

**Comment by jfloff** [comment]
Would you mind sharing a minimal working example so it’s easier for me to debug?

**Comment by alexisfrjp** [comment]
Sorry, I am using an already build app, I don't have any example. Let me make a simple Dockerfile.

**Comment by jfloff** [comment]
Hi there. I just released a new version of the image, could you test that with your already built app? 

Thanks!

**Comment by alexisfrjp** [comment]
Perfect, it's working but I forgot to check the size.
I've used https://github.com/ytdl-org/youtube-dl
I guess it's difficult to keep an image as small as possible without removing what some apps would need and others wouldn't need.

Thanks!

**Comment by jfloff** [comment]
> I guess it's difficult to keep an image as small as possible without removing what some apps would need and others wouldn't need.

That's true and that's why feedback is so important :)

Thanks!
