### ISSUE TITLE
[BUG] Incorrect path for python binaries

### ISSUE THREAD

**Issue by slowr** [jfloff/alpine-python#46]
We are using the python3.6 container and until yesterday everything was running fine. 

Now installing pip packages that have binaries like `gunicorn` no longer works.

Before:
```
bash-4.4# pip install gunicorn
...
Successfully installed gunicorn-19.9.0
bash-4.4# which gunicorn
/usr/local/bin/gunicorn
bash-4.4#
```
After:
```
bash-4.4# pip install gunicorn
...
Successfully installed gunicorn-19.9.0
bash-4.4# which gunicorn
bash-4.4#
```

**Comment by slowr** [comment]
After searching more about the cause of the issue I found out that inside the Dockerfile you run:
```
ln -s /usr/local/lib/pyenv/versions/$PYTHON_VERSION/bin/* $PYTHON_PATH ;\
```
Which doesn't support the cases where we install new files in the bin folder. I am going to issue a quick PR soon.

**Comment by vkotronis** [comment]
I have exactly the same problem with @slowr , the PATH variable needs to be corrected.
