### ISSUE TITLE
how to deal with private repository dependencies

### ISSUE THREAD

**Issue by allan-simon** [jfloff/alpine-python#5]
For example I have a pip module on my private gitlab that I install by doing 

```
pip install git+ssh://git@gitlab.example.com/something/mymodule.git
```

does the current slim image handle this case, without needing to bake git in the final container ?

**Comment by jfloff** [comment]
I really haven't tested that use case, since I don't have any private repos, and I'm not really familiar with `slim` tag (it is @tprobinson child) but from what I can see it should be no problem.

Since we can set private repositories like this in your `requirements.txt` ([ref](http://stackoverflow.com/a/34518202/1700053)): `-e git+ssh://git@gitlab.example.com/something/mymodule.git#egg=mymodule`

That would mean that you could run the slim image like it's written in the readme:
```shell
echo '-e git+ssh://git@gitlab.example.com/something/mymodule.git#egg=mymodule`' > requirements.txt
docker run --rm -ti \
  -v requirements.txt:/requirements.txt \
  jfloff/alpine-python:2.7-slim python hello.py
```


Could you test this and answer back if it works?

Thank you,

**Comment by jfloff** [comment]
Did this work @allan-simon ?

**Comment by allan-simon** [comment]
it seems to need a ssh client, i'm trying to find a ssh package but it seems "ssh" does not exist as a package :/

**Comment by tprobinson** [comment]
Hello,

You can find the names for Alpine's packages here: https://pkgs.alpinelinux.org/packages
SSH's client is in `openssh-client`.

About the slim image and how it deals with requirements.txt: it just passes that file along to `pip -r` essentially, so anything that will work with `pip -r` will work with the slim image.

**Comment by jfloff** [comment]
Thank you for the help @tprobinson.

@allan-simon When you arrive a full-solution if you could post here for future reference would be great!

**Comment by allan-simon** [comment]
yes, I got it working yesterday night

it now looks like that 

```
FROM jfloff/alpine-python:latest-slim 
COPY requirements.txt /requirements.txt

# used to clone the private dependencies
COPY id_rsa /root/.ssh/id_rsa
COPY known_hosts /root/.ssh/known_hosts

COPY myapp/ /myapp

RUN /entrypoint.sh \
  -b git \
  -b openssh-client \
  -b libffi-dev \
  -b openssl-dev \
&& echo

EXPOSE 8888
CMD ["python", "-m" , "myapp"]
```

   * `id_rsa` => a `chmod 600` deploy key with read only access to the private dependencies
   * `known_hosts` a file containing the result of `ssh-keyscan mygitlab.example.com > known_hosts` so that git cloning does not complain it does not know the host 
   * `myapp` is my app with a `__main__.py` inside (so i can run it as a module)

**Comment by jfloff** [comment]
Great stuff! If you can, consider doing a PR with these instructions added to the README, I think they might be useful for other people :)

Thank you for the feedback!
