### ISSUE TITLE
getting error with tzdata and apscheduler library

### ISSUE THREAD

**Issue by scottdickerson** [jfloff/alpine-python#50]
Trying to use the python apscheduler library with your 3.7 image and getting this error.

I've manually added tzdata to the docker image, but I'm having no luck. Any ideas? 

 raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'

**Comment by scottdickerson** [comment]
adding tzdata and RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime fixed my problem, but maybe we can do by default?

**Comment by jfloff** [comment]
Looks easy enough. What about other timezones? Do you have any solution for that, that you might be able to submit a PR?

Thanks!

**Comment by scottdickerson** [comment]
for my specific usecase, and I would guess most others, the timezone reported really doesn't matter too much, I just need some timezone to exist (and the timezone libraries) so any python libraries that depend on it can execute

**Comment by jfloff** [comment]
I see! I will be looking to add this when I have a little bit of free time.

**Comment by jfloff** [comment]
Do you have any quick code which I could use to test out these changes?

**Comment by Icebreaker454** [comment]
> adding tzdata and RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime fixed my problem, but maybe we can do by default?

Thanks a lot, it helped me as well

**Comment by jfloff** [comment]
> Do you have any quick code which I could use to test out these changes?

For reference here is the MWE that I've used to test this change:
```
$ pip install tzlocal
$ python
>>> from tzlocal import get_localzone
>>> tz = get_localzone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/pyenv/versions/3.7.2/lib/python3.7/site-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/pyenv/versions/3.7.2/lib/python3.7/site-packages/tzlocal/unix.py", line 125, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

I added @scottdickerson changes to the image. Going through Hub right now! Thanks!
