### ISSUE TITLE
more information about where the python console error and out go

### ISSUE THREAD

**Issue by scottdickerson** [jfloff/alpine-python#51]
my docker image is built on yours, and runs a long running python script

here's my docker file
```
FROM jfloff/alpine-python:3.7

WORKDIR /

COPY requirements.txt ./
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev tzdata
RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./bmschecks/validateServers.py" ]
```

Unlike the default python docker image the console out doesn't seem to be returned to the command line/standard docker logs.  Can you add some information to the README describing how to access standard out?

**Comment by scottdickerson** [comment]
my bad, this was just a rookie docker mistake, once I passed the run command options correctly it worked fine

**Comment by jfloff** [comment]
👍
