### ISSUE TITLE
Packages purging

### ISSUE THREAD

**Issue by dbrennand** [jfloff/alpine-python#57]
Hi,

Upon building the image and making a first run, the initial script seems to be purging git and other packages which I require.

I believe it might be something to do with this line in entrypoint.sh:
```
# Remove packages that were only required for build.
  apk del $APK_FLAGS $BUILD_PACKAGES "${BUILD_REQUIREMENTS[@]}"
```

**Comment by jfloff** [comment]
There are some packages that are just used to build the image, and are then removed so we keep the container size small - it's intentional. Usually I just add packages that are required by a majority of tools. You can always add them later in your own dockerfile.

**Comment by dbrennand** [comment]
Hi @jfloff 

I am using my own dockerfile.

```
FROM jfloff/alpine-python:3.7-slim
# Install dependencies.
RUN apk update && apk upgrade && \
    apk --no-cache add \
    gcc \
    musl-dev \
    libc-dev \
    libc6-compat \
    linux-headers \
    build-base \
    git \
    libffi-dev \ 
    openssl-dev \
    openssh && \ 
    rm -rf /var/cache/apk/* && pip install ansible && ssh-keygen -t rsa
```

When I run the image, git is removed.

**Comment by dbrennand** [comment]
Hi @jfloff, I think I see now. Do I need to be passing args `-b` or `-p` to the `entrypoint.sh` script?

**Comment by dbrennand** [comment]
Hi @jfloff, 
Trying to pass args to entrypoint.sh is producing `/bin/sh: /entrypoint.sh: Permission denied`. Similar to issue [#2](https://github.com/jfloff/alpine-python/issues/2#issuecomment-252583966)

**Comment by jfloff** [comment]
First: yes, there is an issue with the `entrypoint.sh` I'm going to fix that today.

Second: the `slim` tag was not really designed to be used as a base image. For that you should use the standard tag. If you want to use the slim tag you should use the `entrypoint.sh`. I guess you already figure this out :)

**Comment by dbrennand** [comment]
Hi @jfloff,

Thanks for the response. Am I correct in assuming when I specify git to entrypoint.sh using the -a argument, this will no longer purge it once I run the container?

**Comment by jfloff** [comment]
Yup! https://github.com/jfloff/alpine-python#run-time-dependencies

**Comment by dbrennand** [comment]
Cool, I will be awaiting that fix then 😉 😄

**Comment by jfloff** [comment]
Would you mind pulling the new images and testing if `entrypoint.sh` is now working?

**Comment by dbrennand** [comment]
Entrypoint.sh is now working but git still gets purged 😢

**Comment by jfloff** [comment]
Hang in there :) Releasing a new version so you can test

**Comment by jfloff** [comment]
There you go!

**Comment by dbrennand** [comment]
Pull again yeah? :-)

**Comment by jfloff** [comment]
Sorry 😅

**Comment by dbrennand** [comment]
The script cleans up the build requirements ```apk del --no-cache --no-progress build-base linux-headers libc6-compat git gcc musl-dev libc-dev libc6-compat libffi-dev openssl-dev```

Then installs the APK requirements which is also installs ```+ Installing APK requirements...
apk add --no-cache --no-progress build-base linux-headers libc6-compat git git```

Shouldn't the line be just be ```apk add $APK_FLAGS "${APK_REQUIREMENTS[@]}"``` ???

**Comment by jfloff** [comment]
You are right, that's what I get from doing 10 things at the same time... I'm sorry about the back and forth, and for using you as my guinea pig. 

Let's try now 👍 Already pushed, try pulling and check if it works

**Comment by dbrennand** [comment]
It's all good 😄 no need to apologise.

Build successful for my first dockerfile. Now to test the other😃

**Comment by jfloff** [comment]
Good :) Keep me posted and feel free to close if everything is alright
