### ISSUE TITLE
Passing a repository during install of pip dependencies

### ISSUE THREAD

**Issue by dbrennand** [jfloff/alpine-python#58]
Hello,

Can I use the `-p` flag to install a specific branch from git. For example with ansible. Could I do `-p git+https://github.com/ansible/ansible.git@devel` ?

**Comment by jfloff** [comment]
Mmm good question, I guess you are talking about the `slim` tag? Never tried to do that

**Comment by dbrennand** [comment]
Confirmed, it works.
