### ISSUE TITLE
chmod +x  was needed for entry.point for  latest-slim

### ISSUE THREAD

**Issue by allan-simon** [jfloff/alpine-python#6]
I think it's not intended as the README.md was not precising it for building child image

**Comment by jfloff** [comment]
Great catch, some of the `entrypoint.sh` didn't had execution privileges (`chmod +x`) set correctly. Fixed on next build!

**Comment by allan-simon** [comment]
thanks for the quickfix :)

**Comment by allan-simon** [comment]
fix is again needed in latest version of "latest-slim" :)  (funny I was writing the bug report and had a "déjà-vu" )
