### ISSUE TITLE
python2-dev missing when instantiating alpine-python:2.7-slim

### ISSUE THREAD

**Issue by pieterdd** [jfloff/alpine-python#9]
This happens when I try to instantiate an alpine-python:2.7-slim image:

```bash
> docker run --rm -ti jfloff/alpine-python:2.7-slim bash
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  python2-dev (missing):
    required by: world[python2-dev]
```

Am I using the image incorrectly or is this a bug?

**Comment by jfloff** [comment]
Hello,

Sorry for the delayed response. Some of the packages transitioned from Alpine 3.4 to 3.5 repository. I've updated all the images to take this into account. This should work now. 

Closing now. Feel free to re-open if it's not working.
